# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckbox():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_checkbox(self):
    self.driver.get("https://www.t1.dreame.com/story/1462705664-his-fated-luna/0800850432-chapter-6-%E2%80%93-outing-with-the-stalker.html")
    self.driver.set_window_size(1936, 1056)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ChapterBatchPayBtns_pay-btn__zocF7 > span").click()
    self.vars["win210"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win210"])
    self.driver.find_element(By.CSS_SELECTOR, "label").click()
    self.driver.find_element(By.CSS_SELECTOR, "label").click()
    self.driver.find_element(By.CSS_SELECTOR, "label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-email > .text").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) input").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) input").send_keys("594568079@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) input").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) input").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".email-btn").click()
  
