# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_(self):
    self.driver.get("https://www.t1.dreame.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.execute_script("window.scrollTo(0,1)")
    self.driver.execute_script("window.scrollTo(0,1280)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".List_list-item__HAI1G:nth-child(2) > .List_book-info__xIdCh").click()
    self.vars["win6327"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6327"])
    self.driver.find_element(By.LINK_TEXT, "Start Reading").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_cid__next__modei > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".chap-list-btn > .dreame-font").click()
    self.driver.execute_script("window.scrollTo(0,2200)")
    self.driver.find_element(By.CSS_SELECTOR, ".ChapterListDesktop_chapter-list-item__mcfys:nth-child(12) > a").click()
    self.driver.execute_script("window.scrollTo(0,3)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ChapterBatchPayBtns_pay-btn__zocF7 > span").click()
    self.vars["win1246"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1246"])
    self.driver.find_element(By.NAME, "email").send_keys("594568079@qq.com")
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, "label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-email > .text").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) input").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) input").click()
    element = self.driver.find_element(By.ID, "pcWrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "pcWrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "pcWrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "pcWrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) input").send_keys("594568079@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) input").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) input").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".email-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next .dreame-font").click()
    self.driver.execute_script("window.scrollTo(0,3)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".Header_user-avatar__Gpa0B .rc-image-img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".rc-dropdown-open .rc-image-img").click()
  
